val city ="Adiyaman"
val country ="Turkey"
val phone = 5555555555
val zipCode = 221
val email="ozgermustafa118@gmail.com"
val job="Engineer"
val amountOfStok=2
var balance= 23
val birthday="10.04.2000"
var salary=1333
var maritalStatus="married"
var productComment="good"
val paymentDate="21.03.2023"
var payment =true
var amountOrder= 4
val carModel="A3"
val bookName="blood sweat and pixels"
val publishedDate="20.03.2034"
var discountAmount="0.5"
val roomAmount=4
val latitude=11
val longitude=30
val productName="Test"
val foodPrice=40
val brand="Audi"
val musicName=""
val videoDuration=12
val pruductRating=3.3f
val picturename="test"
val fileFormat="exe"
val color="red"
val colorCode="#000000"
val phoneModel="S22+"
val screenSize="16 inc"
val weight = 34
val nationalDay="Zafer Bayramı"
val holidayDay="sunday"
val reservationDay="10.03.2023"
val streetName="Kurtuluş"
val busLine= "LF10"
var remainMinute=52
val trackingCode=2354353213
val couponDuration=31
val couponCode="HELLOWORLD"
val billAdres="Adiyaman"



